<?php
// 해킹은 범죄입니다. LLNKKR 서비스와 API를 악용하지 마세요.
declare(strict_types=1);
const LLNK_DB_HOST = 'localhost';
const LLNK_DB_NAME = 'CHANGE_ME';
const LLNK_DB_USER = 'CHANGE_ME';
const LLNK_DB_PASS = 'CHANGE_ME';
const LLNK_DB_CHARSET = 'utf8mb4';

const LLNK_BASE_URL = 'https://example.com';
const LLNK_MAX_TARGET_LENGTH = 2048;
const LLNK_IMAGE_CODE_LENGTH = 4;
const LLNK_URL_CODE_LENGTH = 5;
const LLNK_URL_DAILY_LIMIT = 30;
const LLNK_PUBLIC_API_ANONYMOUS_DAILY_LIMIT = 300;
const LLNK_PUBLIC_API_KEY_DAILY_LIMIT = 3000;
const LLNK_PUBLIC_API_KEY_MINUTE_LIMIT = 300;
const LLNK_PUBLIC_API_KEY_BURST_LIMIT = 60;
const LLNK_EXTENSION_IMAGE_DAILY_LIMIT = 100;
const LLNK_PUBLIC_IMAGE_UPLOAD_MINUTE_LIMIT = 5;
const LLNK_PUBLIC_IMAGE_UPLOAD_DAILY_LIMIT = 30;
const LLNK_PUBLIC_FILE_UPLOAD_MINUTE_LIMIT = 5;
const LLNK_PUBLIC_FILE_UPLOAD_DAILY_LIMIT = 50;
const LLNK_ENTRY_UPLOAD_USERNAME = 'CHANGE_ME';
const LLNK_ENTRY_UPLOAD_PASSWORD = 'CHANGE_ME';
const LLNK_POLL_CODE_LENGTH = 7;
const LLNK_POLL_CREATE_MINUTE_LIMIT = 5;
const LLNK_POLL_CREATE_DAILY_LIMIT = 30;
const LLNK_POLL_VOTE_MINUTE_LIMIT = 60;
const LLNK_IMAGE_LOOKUP_MISS_PER_MINUTE = 20;
const LLNK_IMAGE_LOOKUP_MISS_PER_HOUR = 120;
const LLNK_IMAGE_LOOKUP_BLOCK_SECONDS = 3600;
const LLNK_REQUEST_SESSION_GAP_SECONDS = 600;
const LLNK_REQUEST_RATE_PER_MINUTE = 240;
const LLNK_REQUEST_RATE_PER_TEN_MINUTES = 600;
const LLNK_REQUEST_RATE_BLOCK_SECONDS = 600;
const LLNK_TRUST_PROXY_HEADERS = false;
const LLNK_PLACE_TURNSTILE_SITE_KEY = '';
const LLNK_PLACE_TURNSTILE_SECRET_KEY = '';
const LLNK_PLACE_TURNSTILE_HOSTNAME = 'example.com';
const LLNK_PLACE_TURNSTILE_PAINT_INTERVAL = 20;
const LLNK_PLACE_TURNSTILE_SESSION_SECONDS = 1800;

// Generate one private random value for the live server and never publish it.
const LLNK_NEWS_IP_SECRET = 'CHANGE_TO_A_RANDOM_SECRET_OF_AT_LEAST_32_CHARACTERS';
const LLNK_POLL_IP_SECRET = 'CHANGE_TO_ANOTHER_RANDOM_SECRET_OF_AT_LEAST_32_CHARACTERS';

// VANTA room creation and Firebase custom authentication. Keep every value private.
const LLNK_VANTA_IP_SECRET = 'CHANGE_TO_A_THIRD_RANDOM_SECRET_OF_AT_LEAST_32_CHARACTERS';
const LLNK_VANTA_FIREBASE_API_KEY = 'CHANGE_TO_FIREBASE_WEB_API_KEY';
const LLNK_VANTA_FIREBASE_DATABASE_URL = 'https://CHANGE_ME-default-rtdb.asia-southeast1.firebasedatabase.app';
const LLNK_VANTA_FIREBASE_CLIENT_EMAIL = 'CHANGE_ME@CHANGE_ME.iam.gserviceaccount.com';
const LLNK_VANTA_FIREBASE_PRIVATE_KEY_BASE64 = 'CHANGE_TO_BASE64_ENCODED_SERVICE_ACCOUNT_PRIVATE_KEY';
// Cursor A is isolated so high-frequency pointer traffic does not consume Sync A's
// Realtime Database allowance. The extension never sees these values.
const LLNK_VANTA_CURSOR_FIREBASE_DATABASE_URL = 'https://CHANGE_CURSOR_A-default-rtdb.asia-southeast1.firebasedatabase.app';
const LLNK_VANTA_CURSOR_FIREBASE_API_KEY = 'CHANGE_TO_CURSOR_FIREBASE_WEB_API_KEY';
const LLNK_VANTA_CURSOR_FIREBASE_CLIENT_EMAIL = 'CHANGE_ME@CHANGE_CURSOR_A.iam.gserviceaccount.com';
const LLNK_VANTA_CURSOR_FIREBASE_PRIVATE_KEY_BASE64 = 'CHANGE_TO_BASE64_ENCODED_CURSOR_SERVICE_ACCOUNT_PRIVATE_KEY';
// Optional future shards. Add them on the server, then switch new rooms from
// /vanta777 without publishing another extension update.
const LLNK_VANTA_FIREBASE_API_KEY_B = 'CHANGE_TO_SYNC_B_FIREBASE_WEB_API_KEY';
const LLNK_VANTA_FIREBASE_DATABASE_URL_B = 'https://CHANGE_SYNC_B-default-rtdb.asia-southeast1.firebasedatabase.app';
const LLNK_VANTA_FIREBASE_CLIENT_EMAIL_B = 'CHANGE_ME@CHANGE_SYNC_B.iam.gserviceaccount.com';
const LLNK_VANTA_FIREBASE_PRIVATE_KEY_BASE64_B = 'CHANGE_TO_BASE64_ENCODED_SYNC_B_PRIVATE_KEY';
// Separate HMAC key used only by the laptop Firebase Console usage reporter.
const LLNK_VANTA_FIREBASE_USAGE_REPORT_SECRET = 'CHANGE_TO_RANDOM_USAGE_REPORT_SECRET';
const LLNK_VANTA_CURSOR_FIREBASE_API_KEY_B = 'CHANGE_TO_CURSOR_B_FIREBASE_WEB_API_KEY';
const LLNK_VANTA_CURSOR_FIREBASE_DATABASE_URL_B = 'https://CHANGE_CURSOR_B-default-rtdb.asia-southeast1.firebasedatabase.app';
const LLNK_VANTA_CURSOR_FIREBASE_CLIENT_EMAIL_B = 'CHANGE_ME@CHANGE_CURSOR_B.iam.gserviceaccount.com';
const LLNK_VANTA_CURSOR_FIREBASE_PRIVATE_KEY_BASE64_B = 'CHANGE_TO_BASE64_ENCODED_CURSOR_B_PRIVATE_KEY';
const LLNK_VANTA_CREATE_INSTALL_DAILY_LIMIT = 100;
const LLNK_VANTA_CREATE_IP_DAILY_LIMIT = 500;
const LLNK_VANTA_CREATE_IP_FIVE_MINUTE_LIMIT = 30;
const LLNK_VANTA_JOIN_IP_MINUTE_LIMIT = 30;
const LLNK_VANTA_JOIN_INSTALL_MINUTE_LIMIT = 10;
const LLNK_VANTA_ROOM_ACCESS_SECONDS = 86400;
// One VANTA token represents 1 MiB of estimated Firebase download traffic.
// The live value can also be changed from /vanta777 without editing this file.
const LLNK_VANTA_DAILY_TOKENS = 100;
